import {
  FaHtml5,
  FaCss3Alt,
  FaJs,
  FaReact,
  FaNodeJs,
  FaCode,
  FaPython,
} from "react-icons/fa";
import {
  SiTailwindcss,
  SiMongodb,
  SiExpress,
  SiTypescript,
  SiNextdotjs,
  SiSupabase,
  SiVercel,
  SiJsonwebtokens,
  SiRedux,
  SiMongoose,
  SiCloudinary,
  SiAxios,
  SiStreamlit,
  SiPandas,
} from "react-icons/si";

export const TECH_ICONS = {
  "HTML5":              <FaHtml5 className="text-orange-500" />,
  "HTML":               <FaHtml5 className="text-orange-500" />,
  "CSS3":               <FaCss3Alt className="text-blue-500" />,
  "CSS Variables":      <FaCss3Alt className="text-blue-500" />,
  "CSS Grid":           <FaCss3Alt className="text-blue-500" />,
  "JavaScript":         <FaJs className="text-yellow-400" />,
  "JavaScript (ES6+)":  <FaJs className="text-yellow-400" />,
  "DOM Manipulation":   <FaCode className="text-purple-400" />,
  "REST APIs":          <FaCode className="text-cyan-400" />,
  "React.js":           <FaReact className="text-cyan-400" />,
  "React 18":           <FaReact className="text-cyan-400" />,
  "React 19":           <FaReact className="text-cyan-400" />,
  "Node.js":            <FaNodeJs className="text-green-500" />,
  "Express.js":         <SiExpress className="text-gray-300" />,
  "MongoDB":            <SiMongodb className="text-green-400" />,
  "Tailwind CSS":       <SiTailwindcss className="text-sky-400" />,
  "JWT Auth":           <SiJsonwebtokens className="text-pink-400" />,
  "Next.js 14":         <SiNextdotjs className="text-white" />,
  "TypeScript":         <SiTypescript className="text-blue-400" />,
  "Supabase":           <SiSupabase className="text-emerald-400" />,
  "Vercel":             <SiVercel className="text-white" />,
  "Redux Toolkit":      <SiRedux className="text-purple-500" />,
  "Mongoose":           <SiMongoose className="text-orange-300" />,
  "Cloudinary":         <SiCloudinary className="text-blue-400" />,
  "Axios":              <SiAxios className="text-purple-400" />,
  "Python":             <FaPython className="text-yellow-400" />,
  "Streamlit":          <SiStreamlit className="text-red-400" />,
  "Pandas":             <SiPandas className="text-cyan-400" />,
  "Rule-based AI":      <FaCode className="text-emerald-400" />,
  "Data Validation":    <FaCode className="text-orange-400" />,
  "CSV Processing":     <FaCode className="text-blue-300" />,
};
